[proxy]
source = "www.primegroup.ru"
target = "http://www.primegroup.ru"
base_path = "/"

[cache]
db_path = "data"
ttl = 3600

[filter]
include = [
    "{\"BatchExec\"",
    "<!DOCTYPE HT"
]

[debug]
#rq_save_path = "requests"
